rpcs:
  - chain_id: 1
    url: "https://eth.drpc.org"
    stream_url: "wss://eth.drpc.org"
    blocktime: 10
  - chain_id: 2
    url: "wss://arb.drpc.org"
    stream_url: "wss://arbitrum-one-rpc.publicnode.com"
    blocktime: 20
logging:
  level: 1
  format: "json"
  file_path: "/var/log/app.log"
