rpcs:
  - chain_id: 1
    url: "http://example.com"
    blocktime: 10
  - chain_id: 2
    url: "http://example2.com"
    blocktime: 20
logging:
  level: 1
  format: "json"
  file_path: "/var/log/app.log"
